@startuml
title MBH diagram ; 2 <= mpid < 2 + N_MBH

|#white|GlobalFit.c|
start
  :// Forked from MPI_Init();

  |#white|GalacticBinaryIO.c|
  :// Reads known-sources file.
  parse_vb_list();

  |#white|MBHWrapper.c|
  :// search_sources.dat found
  // get N_MBH = number of line
  parse_mbh_args();

  |#white|GalacticBinaryIO.c|
  :// Parse any UCB 
  parse();

  |#white|GlobalFit.c|
  :// Allocates GlobalFit TDI AE structures
  alloc_gf_data();

  |#white|GalacticBinaryWrapper.c|
  :// Allocates UCB structures (flags, orbit, chain, data, prior).
  alloc_gbmcmc_data();

  |#white|VerificationBinaryWrapper.c|
  :// Allocates VG structures (flags, orbit, chain_vec, data_vec,_prior_vec, trial_vec, model_vec).
  alloc_vbmcmc_data();

  |#white|MBHWrapper.c|
  :// Allocates MBH structures (data, het, flags, tdi).
  alloc_mbh_data();

  :// Propagates input TDI to all mpids.
  share_data();

  :initialize_mbh_sampler();

  |#white|NoiseWrapper.c|
  :alloc_noise_data();

  repeat
    :// Remove from TDI AET all found signals from last iteration of UCB VGB MBH
    create_residual();

    |#white|MBHWrapper.c|
    :select_mbh_segment();

    :// Keep only noise from related frequencies band
    select_mbh_noise();

    :// cycle = round ( the max time of all VGB MBH UCB process time) / ( time of one update_mbh_sampler() time );

    while (Loop until done 'cycle' time)
      :// MCMC
      update_mbh_sampler();
    endwhile

    |#white|GlobalFit.c|
    :// Receives TDI AE from root process.
    share_gbmcmc_model();

    :// Sends TDI AE from MBH to root process, then from root to all processes (including MBH).
    share_mbh_model();

    :// Receives noise model from root process.
    share_noise_model();

    :// Receives TDI AE from root process.
    share_vbmcmc_model();

  repeat while (GBMCMC steps finished?) is (no)
  ->yes;

stop
@enduml

